// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_accelerator_conv_and_pool_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_27_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_stream_dout,
        img_stream_num_data_valid,
        img_stream_fifo_cap,
        img_stream_empty_n,
        img_stream_read,
        image_r_address0,
        image_r_ce0,
        image_r_we0,
        image_r_d0,
        image_1_address0,
        image_1_ce0,
        image_1_we0,
        image_1_d0,
        image_2_address0,
        image_2_ce0,
        image_2_we0,
        image_2_d0,
        image_3_address0,
        image_3_ce0,
        image_3_we0,
        image_3_d0,
        image_4_address0,
        image_4_ce0,
        image_4_we0,
        image_4_d0,
        image_5_address0,
        image_5_ce0,
        image_5_we0,
        image_5_d0,
        image_6_address0,
        image_6_ce0,
        image_6_we0,
        image_6_d0,
        image_7_address0,
        image_7_ce0,
        image_7_we0,
        image_7_d0,
        image_8_address0,
        image_8_ce0,
        image_8_we0,
        image_8_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] img_stream_dout;
input  [2:0] img_stream_num_data_valid;
input  [2:0] img_stream_fifo_cap;
input   img_stream_empty_n;
output   img_stream_read;
output  [6:0] image_r_address0;
output   image_r_ce0;
output   image_r_we0;
output  [31:0] image_r_d0;
output  [6:0] image_1_address0;
output   image_1_ce0;
output   image_1_we0;
output  [31:0] image_1_d0;
output  [6:0] image_2_address0;
output   image_2_ce0;
output   image_2_we0;
output  [31:0] image_2_d0;
output  [6:0] image_3_address0;
output   image_3_ce0;
output   image_3_we0;
output  [31:0] image_3_d0;
output  [6:0] image_4_address0;
output   image_4_ce0;
output   image_4_we0;
output  [31:0] image_4_d0;
output  [6:0] image_5_address0;
output   image_5_ce0;
output   image_5_we0;
output  [31:0] image_5_d0;
output  [6:0] image_6_address0;
output   image_6_ce0;
output   image_6_we0;
output  [31:0] image_6_d0;
output  [6:0] image_7_address0;
output   image_7_ce0;
output   image_7_we0;
output  [31:0] image_7_d0;
output  [6:0] image_8_address0;
output   image_8_ce0;
output   image_8_we0;
output  [31:0] image_8_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
reg    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln26_fu_233_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    img_stream_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln26_fu_263_p3;
wire   [4:0] select_ln26_1_fu_271_p3;
reg   [1:0] trunc_ln_reg_453;
reg   [1:0] trunc_ln_reg_453_pp0_iter1_reg;
reg   [1:0] trunc_ln_reg_453_pp0_iter2_reg;
reg   [1:0] trunc_ln_reg_453_pp0_iter3_reg;
reg   [1:0] trunc_ln_reg_453_pp0_iter4_reg;
reg   [1:0] trunc_ln_reg_453_pp0_iter5_reg;
reg   [1:0] trunc_ln_reg_453_pp0_iter6_reg;
reg   [1:0] trunc_ln_reg_453_pp0_iter7_reg;
reg   [1:0] trunc_ln27_1_reg_457;
reg   [1:0] trunc_ln27_1_reg_457_pp0_iter1_reg;
reg   [1:0] trunc_ln27_1_reg_457_pp0_iter2_reg;
reg   [1:0] trunc_ln27_1_reg_457_pp0_iter3_reg;
reg   [1:0] trunc_ln27_1_reg_457_pp0_iter4_reg;
reg   [1:0] trunc_ln27_1_reg_457_pp0_iter5_reg;
reg   [1:0] trunc_ln27_1_reg_457_pp0_iter6_reg;
reg   [1:0] trunc_ln27_1_reg_457_pp0_iter7_reg;
wire   [63:0] zext_ln29_2_fu_392_p1;
reg   [4:0] j_fu_80;
wire   [4:0] add_ln27_fu_331_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_j_load;
reg   [4:0] i_fu_84;
reg   [4:0] ap_sig_allocacmp_i_load;
reg   [9:0] indvar_flatten_fu_88;
wire   [9:0] add_ln26_1_fu_239_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
reg    img_stream_read_local;
reg    image_4_we0_local;
wire   [31:0] bitcast_ln29_fu_405_p1;
reg    image_4_ce0_local;
reg    image_3_we0_local;
reg    image_3_ce0_local;
reg    image_5_we0_local;
reg    image_5_ce0_local;
reg    image_1_we0_local;
reg    image_1_ce0_local;
reg    image_r_we0_local;
reg    image_r_ce0_local;
reg    image_2_we0_local;
reg    image_2_ce0_local;
reg    image_7_we0_local;
reg    image_7_ce0_local;
reg    image_6_we0_local;
reg    image_6_ce0_local;
reg    image_8_we0_local;
reg    image_8_ce0_local;
wire   [0:0] icmp_ln27_fu_257_p2;
wire   [4:0] add_ln26_fu_251_p2;
wire   [4:0] mul_ln26_fu_289_p0;
wire   [6:0] mul_ln26_fu_289_p1;
wire   [10:0] mul_ln26_fu_289_p2;
wire   [4:0] mul_ln27_fu_315_p0;
wire   [6:0] mul_ln27_fu_315_p1;
wire   [10:0] mul_ln27_fu_315_p2;
wire   [4:0] grp_fu_279_p2;
wire   [3:0] trunc_ln29_fu_352_p1;
wire   [5:0] tmp_fu_356_p3;
wire   [6:0] tmp_91_fu_364_p3;
wire   [6:0] zext_ln29_fu_372_p1;
wire   [4:0] grp_fu_305_p2;
wire   [6:0] add_ln26_2_fu_376_p2;
wire   [6:0] zext_ln29_1_fu_382_p1;
wire   [6:0] add_ln29_3_fu_386_p2;
reg    grp_fu_279_ce;
reg    grp_fu_305_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [10:0] mul_ln26_fu_289_p00;
wire   [10:0] mul_ln27_fu_315_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 j_fu_80 = 5'd0;
#0 i_fu_84 = 5'd0;
#0 indvar_flatten_fu_88 = 10'd0;
#0 ap_done_reg = 1'b0;
end

cnn_accelerator_urem_5ns_5ns_5_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 5 ))
urem_5ns_5ns_5_9_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln26_1_fu_271_p3),
    .din1(5'd10),
    .ce(grp_fu_279_ce),
    .dout(grp_fu_279_p2)
);

cnn_accelerator_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U17(
    .din0(mul_ln26_fu_289_p0),
    .din1(mul_ln26_fu_289_p1),
    .dout(mul_ln26_fu_289_p2)
);

cnn_accelerator_urem_5ns_5ns_5_9_1 #(
    .ID( 1 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 5 ))
urem_5ns_5ns_5_9_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln26_fu_263_p3),
    .din1(5'd10),
    .ce(grp_fu_305_ce),
    .dout(grp_fu_305_p2)
);

cnn_accelerator_mul_5ns_7ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mul_5ns_7ns_11_1_1_U19(
    .din0(mul_ln27_fu_315_p0),
    .din1(mul_ln27_fu_315_p1),
    .dout(mul_ln27_fu_315_p2)
);

cnn_accelerator_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln26_fu_233_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_84 <= select_ln26_1_fu_271_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_84 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln26_fu_233_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_88 <= add_ln26_1_fu_239_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_88 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln26_fu_233_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_80 <= add_ln27_fu_331_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_80 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln27_1_reg_457 <= {{mul_ln27_fu_315_p2[10:9]}};
        trunc_ln27_1_reg_457_pp0_iter1_reg <= trunc_ln27_1_reg_457;
        trunc_ln_reg_453 <= {{mul_ln26_fu_289_p2[10:9]}};
        trunc_ln_reg_453_pp0_iter1_reg <= trunc_ln_reg_453;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        trunc_ln27_1_reg_457_pp0_iter2_reg <= trunc_ln27_1_reg_457_pp0_iter1_reg;
        trunc_ln27_1_reg_457_pp0_iter3_reg <= trunc_ln27_1_reg_457_pp0_iter2_reg;
        trunc_ln27_1_reg_457_pp0_iter4_reg <= trunc_ln27_1_reg_457_pp0_iter3_reg;
        trunc_ln27_1_reg_457_pp0_iter5_reg <= trunc_ln27_1_reg_457_pp0_iter4_reg;
        trunc_ln27_1_reg_457_pp0_iter6_reg <= trunc_ln27_1_reg_457_pp0_iter5_reg;
        trunc_ln27_1_reg_457_pp0_iter7_reg <= trunc_ln27_1_reg_457_pp0_iter6_reg;
        trunc_ln_reg_453_pp0_iter2_reg <= trunc_ln_reg_453_pp0_iter1_reg;
        trunc_ln_reg_453_pp0_iter3_reg <= trunc_ln_reg_453_pp0_iter2_reg;
        trunc_ln_reg_453_pp0_iter4_reg <= trunc_ln_reg_453_pp0_iter3_reg;
        trunc_ln_reg_453_pp0_iter5_reg <= trunc_ln_reg_453_pp0_iter4_reg;
        trunc_ln_reg_453_pp0_iter6_reg <= trunc_ln_reg_453_pp0_iter5_reg;
        trunc_ln_reg_453_pp0_iter7_reg <= trunc_ln_reg_453_pp0_iter6_reg;
    end
end

always @ (*) begin
    if (((icmp_ln26_fu_233_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 5'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_84;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 5'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_279_ce = 1'b1;
    end else begin
        grp_fu_279_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_305_ce = 1'b1;
    end else begin
        grp_fu_305_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_1_ce0_local = 1'b1;
    end else begin
        image_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd1) & (trunc_ln_reg_453_pp0_iter7_reg == 2'd0))) begin
        image_1_we0_local = 1'b1;
    end else begin
        image_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_2_ce0_local = 1'b1;
    end else begin
        image_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd0) & ~(trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln_reg_453_pp0_iter7_reg == 2'd0))) begin
        image_2_we0_local = 1'b1;
    end else begin
        image_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_3_ce0_local = 1'b1;
    end else begin
        image_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd0) & (trunc_ln_reg_453_pp0_iter7_reg == 2'd1))) begin
        image_3_we0_local = 1'b1;
    end else begin
        image_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_4_ce0_local = 1'b1;
    end else begin
        image_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd1) & (trunc_ln_reg_453_pp0_iter7_reg == 2'd1))) begin
        image_4_we0_local = 1'b1;
    end else begin
        image_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_5_ce0_local = 1'b1;
    end else begin
        image_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd0) & ~(trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln_reg_453_pp0_iter7_reg == 2'd1))) begin
        image_5_we0_local = 1'b1;
    end else begin
        image_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_6_ce0_local = 1'b1;
    end else begin
        image_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln_reg_453_pp0_iter7_reg == 2'd0) & ~(trunc_ln_reg_453_pp0_iter7_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd0))) begin
        image_6_we0_local = 1'b1;
    end else begin
        image_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_7_ce0_local = 1'b1;
    end else begin
        image_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln_reg_453_pp0_iter7_reg == 2'd0) & ~(trunc_ln_reg_453_pp0_iter7_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd1))) begin
        image_7_we0_local = 1'b1;
    end else begin
        image_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_8_ce0_local = 1'b1;
    end else begin
        image_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln_reg_453_pp0_iter7_reg == 2'd0) & ~(trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd0) & ~(trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd1) & ~(trunc_ln_reg_453_pp0_iter7_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_8_we0_local = 1'b1;
    end else begin
        image_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        image_r_ce0_local = 1'b1;
    end else begin
        image_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (trunc_ln27_1_reg_457_pp0_iter7_reg == 2'd0) & (trunc_ln_reg_453_pp0_iter7_reg == 2'd0))) begin
        image_r_we0_local = 1'b1;
    end else begin
        image_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        img_stream_blk_n = img_stream_empty_n;
    end else begin
        img_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        img_stream_read_local = 1'b1;
    end else begin
        img_stream_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln26_1_fu_239_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln26_2_fu_376_p2 = (tmp_91_fu_364_p3 + zext_ln29_fu_372_p1);

assign add_ln26_fu_251_p2 = (ap_sig_allocacmp_i_load + 5'd1);

assign add_ln27_fu_331_p2 = (select_ln26_fu_263_p3 + 5'd1);

assign add_ln29_3_fu_386_p2 = (add_ln26_2_fu_376_p2 + zext_ln29_1_fu_382_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state9_pp0_stage0_iter8));
end

always @ (*) begin
    ap_block_state9_pp0_stage0_iter8 = (img_stream_empty_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln29_fu_405_p1 = img_stream_dout;

assign icmp_ln26_fu_233_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_257_p2 = ((ap_sig_allocacmp_j_load == 5'd28) ? 1'b1 : 1'b0);

assign image_1_address0 = zext_ln29_2_fu_392_p1;

assign image_1_ce0 = image_1_ce0_local;

assign image_1_d0 = bitcast_ln29_fu_405_p1;

assign image_1_we0 = image_1_we0_local;

assign image_2_address0 = zext_ln29_2_fu_392_p1;

assign image_2_ce0 = image_2_ce0_local;

assign image_2_d0 = bitcast_ln29_fu_405_p1;

assign image_2_we0 = image_2_we0_local;

assign image_3_address0 = zext_ln29_2_fu_392_p1;

assign image_3_ce0 = image_3_ce0_local;

assign image_3_d0 = bitcast_ln29_fu_405_p1;

assign image_3_we0 = image_3_we0_local;

assign image_4_address0 = zext_ln29_2_fu_392_p1;

assign image_4_ce0 = image_4_ce0_local;

assign image_4_d0 = bitcast_ln29_fu_405_p1;

assign image_4_we0 = image_4_we0_local;

assign image_5_address0 = zext_ln29_2_fu_392_p1;

assign image_5_ce0 = image_5_ce0_local;

assign image_5_d0 = bitcast_ln29_fu_405_p1;

assign image_5_we0 = image_5_we0_local;

assign image_6_address0 = zext_ln29_2_fu_392_p1;

assign image_6_ce0 = image_6_ce0_local;

assign image_6_d0 = bitcast_ln29_fu_405_p1;

assign image_6_we0 = image_6_we0_local;

assign image_7_address0 = zext_ln29_2_fu_392_p1;

assign image_7_ce0 = image_7_ce0_local;

assign image_7_d0 = bitcast_ln29_fu_405_p1;

assign image_7_we0 = image_7_we0_local;

assign image_8_address0 = zext_ln29_2_fu_392_p1;

assign image_8_ce0 = image_8_ce0_local;

assign image_8_d0 = bitcast_ln29_fu_405_p1;

assign image_8_we0 = image_8_we0_local;

assign image_r_address0 = zext_ln29_2_fu_392_p1;

assign image_r_ce0 = image_r_ce0_local;

assign image_r_d0 = bitcast_ln29_fu_405_p1;

assign image_r_we0 = image_r_we0_local;

assign img_stream_read = img_stream_read_local;

assign mul_ln26_fu_289_p0 = mul_ln26_fu_289_p00;

assign mul_ln26_fu_289_p00 = select_ln26_1_fu_271_p3;

assign mul_ln26_fu_289_p1 = 11'd52;

assign mul_ln27_fu_315_p0 = mul_ln27_fu_315_p00;

assign mul_ln27_fu_315_p00 = select_ln26_fu_263_p3;

assign mul_ln27_fu_315_p1 = 11'd52;

assign select_ln26_1_fu_271_p3 = ((icmp_ln27_fu_257_p2[0:0] == 1'b1) ? add_ln26_fu_251_p2 : ap_sig_allocacmp_i_load);

assign select_ln26_fu_263_p3 = ((icmp_ln27_fu_257_p2[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_j_load);

assign tmp_91_fu_364_p3 = {{trunc_ln29_fu_352_p1}, {3'd0}};

assign tmp_fu_356_p3 = {{grp_fu_279_p2}, {1'd0}};

assign trunc_ln29_fu_352_p1 = grp_fu_279_p2[3:0];

assign zext_ln29_1_fu_382_p1 = grp_fu_305_p2;

assign zext_ln29_2_fu_392_p1 = add_ln29_3_fu_386_p2;

assign zext_ln29_fu_372_p1 = tmp_fu_356_p3;

endmodule //cnn_accelerator_conv_and_pool_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_27_2
