-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_accelerator is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 4;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    s_axi_ctrl_AWVALID : IN STD_LOGIC;
    s_axi_ctrl_AWREADY : OUT STD_LOGIC;
    s_axi_ctrl_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_WVALID : IN STD_LOGIC;
    s_axi_ctrl_WREADY : OUT STD_LOGIC;
    s_axi_ctrl_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_ctrl_ARVALID : IN STD_LOGIC;
    s_axi_ctrl_ARREADY : OUT STD_LOGIC;
    s_axi_ctrl_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_ctrl_RVALID : OUT STD_LOGIC;
    s_axi_ctrl_RREADY : IN STD_LOGIC;
    s_axi_ctrl_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_ctrl_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_ctrl_BVALID : OUT STD_LOGIC;
    s_axi_ctrl_BREADY : IN STD_LOGIC;
    s_axi_ctrl_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC );
end;


architecture behav of cnn_accelerator is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "cnn_accelerator_cnn_accelerator,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.016000,HLS_SYN_LAT=4138,HLS_SYN_TPT=4083,HLS_SYN_MEM=270,HLS_SYN_DSP=0,HLS_SYN_FF=17765,HLS_SYN_LUT=17118,HLS_VERSION=2024_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal read_input_U0_ap_start : STD_LOGIC;
    signal read_input_U0_ap_done : STD_LOGIC;
    signal read_input_U0_ap_continue : STD_LOGIC;
    signal read_input_U0_ap_idle : STD_LOGIC;
    signal read_input_U0_ap_ready : STD_LOGIC;
    signal read_input_U0_img_stream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal read_input_U0_img_stream_write : STD_LOGIC;
    signal read_input_U0_start_out : STD_LOGIC;
    signal read_input_U0_start_write : STD_LOGIC;
    signal read_input_U0_in_stream_TREADY : STD_LOGIC;
    signal conv_and_pool_U0_ap_start : STD_LOGIC;
    signal conv_and_pool_U0_ap_done : STD_LOGIC;
    signal conv_and_pool_U0_ap_continue : STD_LOGIC;
    signal conv_and_pool_U0_ap_idle : STD_LOGIC;
    signal conv_and_pool_U0_ap_ready : STD_LOGIC;
    signal conv_and_pool_U0_start_out : STD_LOGIC;
    signal conv_and_pool_U0_start_write : STD_LOGIC;
    signal conv_and_pool_U0_img_stream_read : STD_LOGIC;
    signal conv_and_pool_U0_pool_stream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal conv_and_pool_U0_pool_stream_write : STD_LOGIC;
    signal dense_and_write_U0_ap_start : STD_LOGIC;
    signal dense_and_write_U0_ap_done : STD_LOGIC;
    signal dense_and_write_U0_ap_continue : STD_LOGIC;
    signal dense_and_write_U0_ap_idle : STD_LOGIC;
    signal dense_and_write_U0_ap_ready : STD_LOGIC;
    signal dense_and_write_U0_pool_stream_read : STD_LOGIC;
    signal dense_and_write_U0_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal dense_and_write_U0_out_stream_TVALID : STD_LOGIC;
    signal dense_and_write_U0_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal dense_and_write_U0_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal dense_and_write_U0_out_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dense_and_write_U0_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal dense_and_write_U0_out_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal dense_and_write_U0_out_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal img_stream_full_n : STD_LOGIC;
    signal img_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal img_stream_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal img_stream_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal img_stream_empty_n : STD_LOGIC;
    signal pool_stream_full_n : STD_LOGIC;
    signal pool_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal pool_stream_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal pool_stream_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal pool_stream_empty_n : STD_LOGIC;
    signal start_for_conv_and_pool_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_and_pool_U0_full_n : STD_LOGIC;
    signal start_for_conv_and_pool_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_conv_and_pool_U0_empty_n : STD_LOGIC;
    signal start_for_dense_and_write_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_and_write_U0_full_n : STD_LOGIC;
    signal start_for_dense_and_write_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_dense_and_write_U0_empty_n : STD_LOGIC;

    component cnn_accelerator_read_input IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        img_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        img_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_stream_full_n : IN STD_LOGIC;
        img_stream_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cnn_accelerator_conv_and_pool IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        img_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        img_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_stream_empty_n : IN STD_LOGIC;
        img_stream_read : OUT STD_LOGIC;
        pool_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        pool_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        pool_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        pool_stream_full_n : IN STD_LOGIC;
        pool_stream_write : OUT STD_LOGIC );
    end component;


    component cnn_accelerator_dense_and_write IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pool_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        pool_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        pool_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        pool_stream_empty_n : IN STD_LOGIC;
        pool_stream_read : OUT STD_LOGIC;
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cnn_accelerator_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component cnn_accelerator_start_for_conv_and_pool_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component cnn_accelerator_start_for_dense_and_write_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component cnn_accelerator_ctrl_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    ctrl_s_axi_U : component cnn_accelerator_ctrl_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_ctrl_AWVALID,
        AWREADY => s_axi_ctrl_AWREADY,
        AWADDR => s_axi_ctrl_AWADDR,
        WVALID => s_axi_ctrl_WVALID,
        WREADY => s_axi_ctrl_WREADY,
        WDATA => s_axi_ctrl_WDATA,
        WSTRB => s_axi_ctrl_WSTRB,
        ARVALID => s_axi_ctrl_ARVALID,
        ARREADY => s_axi_ctrl_ARREADY,
        ARADDR => s_axi_ctrl_ARADDR,
        RVALID => s_axi_ctrl_RVALID,
        RREADY => s_axi_ctrl_RREADY,
        RDATA => s_axi_ctrl_RDATA,
        RRESP => s_axi_ctrl_RRESP,
        BVALID => s_axi_ctrl_BVALID,
        BREADY => s_axi_ctrl_BREADY,
        BRESP => s_axi_ctrl_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    read_input_U0 : component cnn_accelerator_read_input
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => read_input_U0_ap_start,
        start_full_n => start_for_conv_and_pool_U0_full_n,
        ap_done => read_input_U0_ap_done,
        ap_continue => read_input_U0_ap_continue,
        ap_idle => read_input_U0_ap_idle,
        ap_ready => read_input_U0_ap_ready,
        in_stream_TVALID => in_stream_TVALID,
        img_stream_din => read_input_U0_img_stream_din,
        img_stream_num_data_valid => img_stream_num_data_valid,
        img_stream_fifo_cap => img_stream_fifo_cap,
        img_stream_full_n => img_stream_full_n,
        img_stream_write => read_input_U0_img_stream_write,
        start_out => read_input_U0_start_out,
        start_write => read_input_U0_start_write,
        in_stream_TDATA => in_stream_TDATA,
        in_stream_TREADY => read_input_U0_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP,
        in_stream_TSTRB => in_stream_TSTRB,
        in_stream_TUSER => in_stream_TUSER,
        in_stream_TLAST => in_stream_TLAST,
        in_stream_TID => in_stream_TID,
        in_stream_TDEST => in_stream_TDEST);

    conv_and_pool_U0 : component cnn_accelerator_conv_and_pool
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_and_pool_U0_ap_start,
        start_full_n => start_for_dense_and_write_U0_full_n,
        ap_done => conv_and_pool_U0_ap_done,
        ap_continue => conv_and_pool_U0_ap_continue,
        ap_idle => conv_and_pool_U0_ap_idle,
        ap_ready => conv_and_pool_U0_ap_ready,
        start_out => conv_and_pool_U0_start_out,
        start_write => conv_and_pool_U0_start_write,
        img_stream_dout => img_stream_dout,
        img_stream_num_data_valid => img_stream_num_data_valid,
        img_stream_fifo_cap => img_stream_fifo_cap,
        img_stream_empty_n => img_stream_empty_n,
        img_stream_read => conv_and_pool_U0_img_stream_read,
        pool_stream_din => conv_and_pool_U0_pool_stream_din,
        pool_stream_num_data_valid => pool_stream_num_data_valid,
        pool_stream_fifo_cap => pool_stream_fifo_cap,
        pool_stream_full_n => pool_stream_full_n,
        pool_stream_write => conv_and_pool_U0_pool_stream_write);

    dense_and_write_U0 : component cnn_accelerator_dense_and_write
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => dense_and_write_U0_ap_start,
        ap_done => dense_and_write_U0_ap_done,
        ap_continue => dense_and_write_U0_ap_continue,
        ap_idle => dense_and_write_U0_ap_idle,
        ap_ready => dense_and_write_U0_ap_ready,
        pool_stream_dout => pool_stream_dout,
        pool_stream_num_data_valid => pool_stream_num_data_valid,
        pool_stream_fifo_cap => pool_stream_fifo_cap,
        pool_stream_empty_n => pool_stream_empty_n,
        pool_stream_read => dense_and_write_U0_pool_stream_read,
        out_stream_TDATA => dense_and_write_U0_out_stream_TDATA,
        out_stream_TVALID => dense_and_write_U0_out_stream_TVALID,
        out_stream_TREADY => out_stream_TREADY,
        out_stream_TKEEP => dense_and_write_U0_out_stream_TKEEP,
        out_stream_TSTRB => dense_and_write_U0_out_stream_TSTRB,
        out_stream_TUSER => dense_and_write_U0_out_stream_TUSER,
        out_stream_TLAST => dense_and_write_U0_out_stream_TLAST,
        out_stream_TID => dense_and_write_U0_out_stream_TID,
        out_stream_TDEST => dense_and_write_U0_out_stream_TDEST);

    img_stream_U : component cnn_accelerator_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => read_input_U0_img_stream_din,
        if_full_n => img_stream_full_n,
        if_write => read_input_U0_img_stream_write,
        if_dout => img_stream_dout,
        if_num_data_valid => img_stream_num_data_valid,
        if_fifo_cap => img_stream_fifo_cap,
        if_empty_n => img_stream_empty_n,
        if_read => conv_and_pool_U0_img_stream_read);

    pool_stream_U : component cnn_accelerator_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => conv_and_pool_U0_pool_stream_din,
        if_full_n => pool_stream_full_n,
        if_write => conv_and_pool_U0_pool_stream_write,
        if_dout => pool_stream_dout,
        if_num_data_valid => pool_stream_num_data_valid,
        if_fifo_cap => pool_stream_fifo_cap,
        if_empty_n => pool_stream_empty_n,
        if_read => dense_and_write_U0_pool_stream_read);

    start_for_conv_and_pool_U0_U : component cnn_accelerator_start_for_conv_and_pool_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_conv_and_pool_U0_din,
        if_full_n => start_for_conv_and_pool_U0_full_n,
        if_write => read_input_U0_start_write,
        if_dout => start_for_conv_and_pool_U0_dout,
        if_empty_n => start_for_conv_and_pool_U0_empty_n,
        if_read => conv_and_pool_U0_ap_ready);

    start_for_dense_and_write_U0_U : component cnn_accelerator_start_for_dense_and_write_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_dense_and_write_U0_din,
        if_full_n => start_for_dense_and_write_U0_full_n,
        if_write => conv_and_pool_U0_start_write,
        if_dout => start_for_dense_and_write_U0_dout,
        if_empty_n => start_for_dense_and_write_U0_empty_n,
        if_read => dense_and_write_U0_ap_ready);




    ap_done <= dense_and_write_U0_ap_done;
    ap_idle <= (read_input_U0_ap_idle and dense_and_write_U0_ap_idle and conv_and_pool_U0_ap_idle);
    ap_ready <= read_input_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    conv_and_pool_U0_ap_continue <= ap_const_logic_1;
    conv_and_pool_U0_ap_start <= start_for_conv_and_pool_U0_empty_n;
    dense_and_write_U0_ap_continue <= ap_const_logic_1;
    dense_and_write_U0_ap_start <= start_for_dense_and_write_U0_empty_n;
    in_stream_TREADY <= read_input_U0_in_stream_TREADY;
    out_stream_TDATA <= dense_and_write_U0_out_stream_TDATA;
    out_stream_TDEST <= dense_and_write_U0_out_stream_TDEST;
    out_stream_TID <= dense_and_write_U0_out_stream_TID;
    out_stream_TKEEP <= dense_and_write_U0_out_stream_TKEEP;
    out_stream_TLAST <= dense_and_write_U0_out_stream_TLAST;
    out_stream_TSTRB <= dense_and_write_U0_out_stream_TSTRB;
    out_stream_TUSER <= dense_and_write_U0_out_stream_TUSER;
    out_stream_TVALID <= dense_and_write_U0_out_stream_TVALID;
    read_input_U0_ap_continue <= ap_const_logic_1;
    read_input_U0_ap_start <= ap_start;
    start_for_conv_and_pool_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_dense_and_write_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
