-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_accelerator_conv_and_pool_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_27_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    img_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    img_stream_empty_n : IN STD_LOGIC;
    img_stream_read : OUT STD_LOGIC;
    image_r_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_r_ce0 : OUT STD_LOGIC;
    image_r_we0 : OUT STD_LOGIC;
    image_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    image_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_1_ce0 : OUT STD_LOGIC;
    image_1_we0 : OUT STD_LOGIC;
    image_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    image_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_2_ce0 : OUT STD_LOGIC;
    image_2_we0 : OUT STD_LOGIC;
    image_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    image_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_3_ce0 : OUT STD_LOGIC;
    image_3_we0 : OUT STD_LOGIC;
    image_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    image_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_4_ce0 : OUT STD_LOGIC;
    image_4_we0 : OUT STD_LOGIC;
    image_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    image_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_5_ce0 : OUT STD_LOGIC;
    image_5_we0 : OUT STD_LOGIC;
    image_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    image_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_6_ce0 : OUT STD_LOGIC;
    image_6_we0 : OUT STD_LOGIC;
    image_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    image_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_7_ce0 : OUT STD_LOGIC;
    image_7_we0 : OUT STD_LOGIC;
    image_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    image_8_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    image_8_ce0 : OUT STD_LOGIC;
    image_8_we0 : OUT STD_LOGIC;
    image_8_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of cnn_accelerator_conv_and_pool_Pipeline_VITIS_LOOP_26_1_VITIS_LOOP_27_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv5_1C : STD_LOGIC_VECTOR (4 downto 0) := "11100";
    constant ap_const_lv5_A : STD_LOGIC_VECTOR (4 downto 0) := "01010";
    constant ap_const_lv11_34 : STD_LOGIC_VECTOR (10 downto 0) := "00000110100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln26_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal img_stream_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln26_fu_263_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln26_1_fu_271_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln_reg_453 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_reg_453_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_reg_453_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_reg_453_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_reg_453_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_reg_453_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_reg_453_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln_reg_453_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_457 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_457_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_457_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_457_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_457_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_457_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_457_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln27_1_reg_457_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln29_2_fu_392_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_80 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln27_fu_331_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (4 downto 0);
    signal i_fu_84 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_fu_88 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln26_1_fu_239_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (9 downto 0);
    signal img_stream_read_local : STD_LOGIC;
    signal image_4_we0_local : STD_LOGIC;
    signal bitcast_ln29_fu_405_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal image_4_ce0_local : STD_LOGIC;
    signal image_3_we0_local : STD_LOGIC;
    signal image_3_ce0_local : STD_LOGIC;
    signal image_5_we0_local : STD_LOGIC;
    signal image_5_ce0_local : STD_LOGIC;
    signal image_1_we0_local : STD_LOGIC;
    signal image_1_ce0_local : STD_LOGIC;
    signal image_r_we0_local : STD_LOGIC;
    signal image_r_ce0_local : STD_LOGIC;
    signal image_2_we0_local : STD_LOGIC;
    signal image_2_ce0_local : STD_LOGIC;
    signal image_7_we0_local : STD_LOGIC;
    signal image_7_ce0_local : STD_LOGIC;
    signal image_6_we0_local : STD_LOGIC;
    signal image_6_ce0_local : STD_LOGIC;
    signal image_8_we0_local : STD_LOGIC;
    signal image_8_ce0_local : STD_LOGIC;
    signal icmp_ln27_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln26_fu_251_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln26_fu_289_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln26_fu_289_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln26_fu_289_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln27_fu_315_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln27_fu_315_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln27_fu_315_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_279_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln29_fu_352_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_356_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_91_fu_364_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_fu_372_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_305_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln26_2_fu_376_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln29_1_fu_382_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln29_3_fu_386_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_279_ce : STD_LOGIC;
    signal grp_fu_305_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln26_fu_289_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln27_fu_315_p00 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component cnn_accelerator_urem_5ns_5ns_5_9_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component cnn_accelerator_mul_5ns_7ns_11_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (4 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        dout : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component cnn_accelerator_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_5ns_5ns_5_9_1_U16 : component cnn_accelerator_urem_5ns_5ns_5_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        dout_WIDTH => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln26_1_fu_271_p3,
        din1 => ap_const_lv5_A,
        ce => grp_fu_279_ce,
        dout => grp_fu_279_p2);

    mul_5ns_7ns_11_1_1_U17 : component cnn_accelerator_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln26_fu_289_p0,
        din1 => mul_ln26_fu_289_p1,
        dout => mul_ln26_fu_289_p2);

    urem_5ns_5ns_5_9_1_U18 : component cnn_accelerator_urem_5ns_5ns_5_9_1
    generic map (
        ID => 1,
        NUM_STAGE => 9,
        din0_WIDTH => 5,
        din1_WIDTH => 5,
        dout_WIDTH => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln26_fu_263_p3,
        din1 => ap_const_lv5_A,
        ce => grp_fu_305_ce,
        dout => grp_fu_305_p2);

    mul_5ns_7ns_11_1_1_U19 : component cnn_accelerator_mul_5ns_7ns_11_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 5,
        din1_WIDTH => 7,
        dout_WIDTH => 11)
    port map (
        din0 => mul_ln27_fu_315_p0,
        din1 => mul_ln27_fu_315_p1,
        dout => mul_ln27_fu_315_p2);

    flow_control_loop_pipe_sequential_init_U : component cnn_accelerator_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    i_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln26_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_84 <= select_ln26_1_fu_271_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_84 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln26_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_88 <= add_ln26_1_fu_239_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_88 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln26_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_80 <= add_ln27_fu_331_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_80 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                trunc_ln27_1_reg_457 <= mul_ln27_fu_315_p2(10 downto 9);
                trunc_ln27_1_reg_457_pp0_iter1_reg <= trunc_ln27_1_reg_457;
                trunc_ln_reg_453 <= mul_ln26_fu_289_p2(10 downto 9);
                trunc_ln_reg_453_pp0_iter1_reg <= trunc_ln_reg_453;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                trunc_ln27_1_reg_457_pp0_iter2_reg <= trunc_ln27_1_reg_457_pp0_iter1_reg;
                trunc_ln27_1_reg_457_pp0_iter3_reg <= trunc_ln27_1_reg_457_pp0_iter2_reg;
                trunc_ln27_1_reg_457_pp0_iter4_reg <= trunc_ln27_1_reg_457_pp0_iter3_reg;
                trunc_ln27_1_reg_457_pp0_iter5_reg <= trunc_ln27_1_reg_457_pp0_iter4_reg;
                trunc_ln27_1_reg_457_pp0_iter6_reg <= trunc_ln27_1_reg_457_pp0_iter5_reg;
                trunc_ln27_1_reg_457_pp0_iter7_reg <= trunc_ln27_1_reg_457_pp0_iter6_reg;
                trunc_ln_reg_453_pp0_iter2_reg <= trunc_ln_reg_453_pp0_iter1_reg;
                trunc_ln_reg_453_pp0_iter3_reg <= trunc_ln_reg_453_pp0_iter2_reg;
                trunc_ln_reg_453_pp0_iter4_reg <= trunc_ln_reg_453_pp0_iter3_reg;
                trunc_ln_reg_453_pp0_iter5_reg <= trunc_ln_reg_453_pp0_iter4_reg;
                trunc_ln_reg_453_pp0_iter6_reg <= trunc_ln_reg_453_pp0_iter5_reg;
                trunc_ln_reg_453_pp0_iter7_reg <= trunc_ln_reg_453_pp0_iter6_reg;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln26_1_fu_239_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv10_1));
    add_ln26_2_fu_376_p2 <= std_logic_vector(unsigned(tmp_91_fu_364_p3) + unsigned(zext_ln29_fu_372_p1));
    add_ln26_fu_251_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv5_1));
    add_ln27_fu_331_p2 <= std_logic_vector(unsigned(select_ln26_fu_263_p3) + unsigned(ap_const_lv5_1));
    add_ln29_3_fu_386_p2 <= std_logic_vector(unsigned(add_ln26_2_fu_376_p2) + unsigned(zext_ln29_1_fu_382_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_state9_pp0_stage0_iter8)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_state9_pp0_stage0_iter8)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8));
    end process;


    ap_block_state9_pp0_stage0_iter8_assign_proc : process(img_stream_empty_n)
    begin
                ap_block_state9_pp0_stage0_iter8 <= (img_stream_empty_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln26_fu_233_p2)
    begin
        if (((icmp_ln26_fu_233_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_84;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_88)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_88;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_80, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_80;
        end if; 
    end process;

    bitcast_ln29_fu_405_p1 <= img_stream_dout;

    grp_fu_279_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_279_ce <= ap_const_logic_1;
        else 
            grp_fu_279_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_305_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_305_ce <= ap_const_logic_1;
        else 
            grp_fu_305_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln26_fu_233_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv10_310) else "0";
    icmp_ln27_fu_257_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv5_1C) else "0";
    image_1_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_1_ce0 <= image_1_ce0_local;

    image_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_1_ce0_local <= ap_const_logic_1;
        else 
            image_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_1_d0 <= bitcast_ln29_fu_405_p1;
    image_1_we0 <= image_1_we0_local;

    image_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_1) and (trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_0))) then 
            image_1_we0_local <= ap_const_logic_1;
        else 
            image_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_2_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_2_ce0 <= image_2_ce0_local;

    image_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_2_ce0_local <= ap_const_logic_1;
        else 
            image_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_2_d0 <= bitcast_ln29_fu_405_p1;
    image_2_we0 <= image_2_we0_local;

    image_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if ((not((trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_0)) and not((trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_0))) then 
            image_2_we0_local <= ap_const_logic_1;
        else 
            image_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_3_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_3_ce0 <= image_3_ce0_local;

    image_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_3_ce0_local <= ap_const_logic_1;
        else 
            image_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_3_d0 <= bitcast_ln29_fu_405_p1;
    image_3_we0 <= image_3_we0_local;

    image_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_0) and (trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_1))) then 
            image_3_we0_local <= ap_const_logic_1;
        else 
            image_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_4_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_4_ce0 <= image_4_ce0_local;

    image_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_4_ce0_local <= ap_const_logic_1;
        else 
            image_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_4_d0 <= bitcast_ln29_fu_405_p1;
    image_4_we0 <= image_4_we0_local;

    image_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_1) and (trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_1))) then 
            image_4_we0_local <= ap_const_logic_1;
        else 
            image_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_5_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_5_ce0 <= image_5_ce0_local;

    image_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_5_ce0_local <= ap_const_logic_1;
        else 
            image_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_5_d0 <= bitcast_ln29_fu_405_p1;
    image_5_we0 <= image_5_we0_local;

    image_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if ((not((trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_0)) and not((trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_1))) then 
            image_5_we0_local <= ap_const_logic_1;
        else 
            image_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_6_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_6_ce0 <= image_6_ce0_local;

    image_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_6_ce0_local <= ap_const_logic_1;
        else 
            image_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_6_d0 <= bitcast_ln29_fu_405_p1;
    image_6_we0 <= image_6_we0_local;

    image_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if ((not((trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_0)) and not((trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_0))) then 
            image_6_we0_local <= ap_const_logic_1;
        else 
            image_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_7_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_7_ce0 <= image_7_ce0_local;

    image_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_7_ce0_local <= ap_const_logic_1;
        else 
            image_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_7_d0 <= bitcast_ln29_fu_405_p1;
    image_7_we0 <= image_7_we0_local;

    image_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if ((not((trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_0)) and not((trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_1))) then 
            image_7_we0_local <= ap_const_logic_1;
        else 
            image_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_8_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_8_ce0 <= image_8_ce0_local;

    image_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_8_ce0_local <= ap_const_logic_1;
        else 
            image_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_8_d0 <= bitcast_ln29_fu_405_p1;
    image_8_we0 <= image_8_we0_local;

    image_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if ((not((trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_0)) and not((trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_0)) and not((trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_1)) and not((trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_8_we0_local <= ap_const_logic_1;
        else 
            image_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_r_address0 <= zext_ln29_2_fu_392_p1(7 - 1 downto 0);
    image_r_ce0 <= image_r_ce0_local;

    image_r_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            image_r_ce0_local <= ap_const_logic_1;
        else 
            image_r_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    image_r_d0 <= bitcast_ln29_fu_405_p1;
    image_r_we0 <= image_r_we0_local;

    image_r_we0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001, trunc_ln_reg_453_pp0_iter7_reg, trunc_ln27_1_reg_457_pp0_iter7_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (trunc_ln27_1_reg_457_pp0_iter7_reg = ap_const_lv2_0) and (trunc_ln_reg_453_pp0_iter7_reg = ap_const_lv2_0))) then 
            image_r_we0_local <= ap_const_logic_1;
        else 
            image_r_we0_local <= ap_const_logic_0;
        end if; 
    end process;


    img_stream_blk_n_assign_proc : process(ap_enable_reg_pp0_iter8, img_stream_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            img_stream_blk_n <= img_stream_empty_n;
        else 
            img_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_stream_read <= img_stream_read_local;

    img_stream_read_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            img_stream_read_local <= ap_const_logic_1;
        else 
            img_stream_read_local <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln26_fu_289_p0 <= mul_ln26_fu_289_p00(5 - 1 downto 0);
    mul_ln26_fu_289_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln26_1_fu_271_p3),11));
    mul_ln26_fu_289_p1 <= ap_const_lv11_34(7 - 1 downto 0);
    mul_ln27_fu_315_p0 <= mul_ln27_fu_315_p00(5 - 1 downto 0);
    mul_ln27_fu_315_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln26_fu_263_p3),11));
    mul_ln27_fu_315_p1 <= ap_const_lv11_34(7 - 1 downto 0);
    select_ln26_1_fu_271_p3 <= 
        add_ln26_fu_251_p2 when (icmp_ln27_fu_257_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln26_fu_263_p3 <= 
        ap_const_lv5_0 when (icmp_ln27_fu_257_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
    tmp_91_fu_364_p3 <= (trunc_ln29_fu_352_p1 & ap_const_lv3_0);
    tmp_fu_356_p3 <= (grp_fu_279_p2 & ap_const_lv1_0);
    trunc_ln29_fu_352_p1 <= grp_fu_279_p2(4 - 1 downto 0);
    zext_ln29_1_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_305_p2),7));
    zext_ln29_2_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln29_3_fu_386_p2),64));
    zext_ln29_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_356_p3),7));
end behav;
