// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cnn_accelerator_cnn_accelerator,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.016000,HLS_SYN_LAT=4138,HLS_SYN_TPT=4083,HLS_SYN_MEM=270,HLS_SYN_DSP=0,HLS_SYN_FF=17765,HLS_SYN_LUT=17118,HLS_VERSION=2024_1}" *)

module cnn_accelerator (
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        in_stream_TDATA,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        in_stream_TVALID,
        in_stream_TREADY,
        out_stream_TVALID,
        out_stream_TREADY
);

parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [31:0] in_stream_TDATA;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input   in_stream_TVALID;
output   in_stream_TREADY;
output   out_stream_TVALID;
input   out_stream_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    read_input_U0_ap_start;
wire    read_input_U0_ap_done;
wire    read_input_U0_ap_continue;
wire    read_input_U0_ap_idle;
wire    read_input_U0_ap_ready;
wire   [31:0] read_input_U0_img_stream_din;
wire    read_input_U0_img_stream_write;
wire    read_input_U0_start_out;
wire    read_input_U0_start_write;
wire    read_input_U0_in_stream_TREADY;
wire    conv_and_pool_U0_ap_start;
wire    conv_and_pool_U0_ap_done;
wire    conv_and_pool_U0_ap_continue;
wire    conv_and_pool_U0_ap_idle;
wire    conv_and_pool_U0_ap_ready;
wire    conv_and_pool_U0_start_out;
wire    conv_and_pool_U0_start_write;
wire    conv_and_pool_U0_img_stream_read;
wire   [31:0] conv_and_pool_U0_pool_stream_din;
wire    conv_and_pool_U0_pool_stream_write;
wire    dense_and_write_U0_ap_start;
wire    dense_and_write_U0_ap_done;
wire    dense_and_write_U0_ap_continue;
wire    dense_and_write_U0_ap_idle;
wire    dense_and_write_U0_ap_ready;
wire    dense_and_write_U0_pool_stream_read;
wire   [31:0] dense_and_write_U0_out_stream_TDATA;
wire    dense_and_write_U0_out_stream_TVALID;
wire   [3:0] dense_and_write_U0_out_stream_TKEEP;
wire   [3:0] dense_and_write_U0_out_stream_TSTRB;
wire   [0:0] dense_and_write_U0_out_stream_TUSER;
wire   [0:0] dense_and_write_U0_out_stream_TLAST;
wire   [0:0] dense_and_write_U0_out_stream_TID;
wire   [0:0] dense_and_write_U0_out_stream_TDEST;
wire    img_stream_full_n;
wire   [31:0] img_stream_dout;
wire   [2:0] img_stream_num_data_valid;
wire   [2:0] img_stream_fifo_cap;
wire    img_stream_empty_n;
wire    pool_stream_full_n;
wire   [31:0] pool_stream_dout;
wire   [2:0] pool_stream_num_data_valid;
wire   [2:0] pool_stream_fifo_cap;
wire    pool_stream_empty_n;
wire   [0:0] start_for_conv_and_pool_U0_din;
wire    start_for_conv_and_pool_U0_full_n;
wire   [0:0] start_for_conv_and_pool_U0_dout;
wire    start_for_conv_and_pool_U0_empty_n;
wire   [0:0] start_for_dense_and_write_U0_din;
wire    start_for_dense_and_write_U0_full_n;
wire   [0:0] start_for_dense_and_write_U0_dout;
wire    start_for_dense_and_write_U0_empty_n;

cnn_accelerator_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cnn_accelerator_read_input read_input_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_input_U0_ap_start),
    .start_full_n(start_for_conv_and_pool_U0_full_n),
    .ap_done(read_input_U0_ap_done),
    .ap_continue(read_input_U0_ap_continue),
    .ap_idle(read_input_U0_ap_idle),
    .ap_ready(read_input_U0_ap_ready),
    .in_stream_TVALID(in_stream_TVALID),
    .img_stream_din(read_input_U0_img_stream_din),
    .img_stream_num_data_valid(img_stream_num_data_valid),
    .img_stream_fifo_cap(img_stream_fifo_cap),
    .img_stream_full_n(img_stream_full_n),
    .img_stream_write(read_input_U0_img_stream_write),
    .start_out(read_input_U0_start_out),
    .start_write(read_input_U0_start_write),
    .in_stream_TDATA(in_stream_TDATA),
    .in_stream_TREADY(read_input_U0_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP),
    .in_stream_TSTRB(in_stream_TSTRB),
    .in_stream_TUSER(in_stream_TUSER),
    .in_stream_TLAST(in_stream_TLAST),
    .in_stream_TID(in_stream_TID),
    .in_stream_TDEST(in_stream_TDEST)
);

cnn_accelerator_conv_and_pool conv_and_pool_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_and_pool_U0_ap_start),
    .start_full_n(start_for_dense_and_write_U0_full_n),
    .ap_done(conv_and_pool_U0_ap_done),
    .ap_continue(conv_and_pool_U0_ap_continue),
    .ap_idle(conv_and_pool_U0_ap_idle),
    .ap_ready(conv_and_pool_U0_ap_ready),
    .start_out(conv_and_pool_U0_start_out),
    .start_write(conv_and_pool_U0_start_write),
    .img_stream_dout(img_stream_dout),
    .img_stream_num_data_valid(img_stream_num_data_valid),
    .img_stream_fifo_cap(img_stream_fifo_cap),
    .img_stream_empty_n(img_stream_empty_n),
    .img_stream_read(conv_and_pool_U0_img_stream_read),
    .pool_stream_din(conv_and_pool_U0_pool_stream_din),
    .pool_stream_num_data_valid(pool_stream_num_data_valid),
    .pool_stream_fifo_cap(pool_stream_fifo_cap),
    .pool_stream_full_n(pool_stream_full_n),
    .pool_stream_write(conv_and_pool_U0_pool_stream_write)
);

cnn_accelerator_dense_and_write dense_and_write_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_and_write_U0_ap_start),
    .ap_done(dense_and_write_U0_ap_done),
    .ap_continue(dense_and_write_U0_ap_continue),
    .ap_idle(dense_and_write_U0_ap_idle),
    .ap_ready(dense_and_write_U0_ap_ready),
    .pool_stream_dout(pool_stream_dout),
    .pool_stream_num_data_valid(pool_stream_num_data_valid),
    .pool_stream_fifo_cap(pool_stream_fifo_cap),
    .pool_stream_empty_n(pool_stream_empty_n),
    .pool_stream_read(dense_and_write_U0_pool_stream_read),
    .out_stream_TDATA(dense_and_write_U0_out_stream_TDATA),
    .out_stream_TVALID(dense_and_write_U0_out_stream_TVALID),
    .out_stream_TREADY(out_stream_TREADY),
    .out_stream_TKEEP(dense_and_write_U0_out_stream_TKEEP),
    .out_stream_TSTRB(dense_and_write_U0_out_stream_TSTRB),
    .out_stream_TUSER(dense_and_write_U0_out_stream_TUSER),
    .out_stream_TLAST(dense_and_write_U0_out_stream_TLAST),
    .out_stream_TID(dense_and_write_U0_out_stream_TID),
    .out_stream_TDEST(dense_and_write_U0_out_stream_TDEST)
);

cnn_accelerator_fifo_w32_d2_S img_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_img_stream_din),
    .if_full_n(img_stream_full_n),
    .if_write(read_input_U0_img_stream_write),
    .if_dout(img_stream_dout),
    .if_num_data_valid(img_stream_num_data_valid),
    .if_fifo_cap(img_stream_fifo_cap),
    .if_empty_n(img_stream_empty_n),
    .if_read(conv_and_pool_U0_img_stream_read)
);

cnn_accelerator_fifo_w32_d2_S pool_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_and_pool_U0_pool_stream_din),
    .if_full_n(pool_stream_full_n),
    .if_write(conv_and_pool_U0_pool_stream_write),
    .if_dout(pool_stream_dout),
    .if_num_data_valid(pool_stream_num_data_valid),
    .if_fifo_cap(pool_stream_fifo_cap),
    .if_empty_n(pool_stream_empty_n),
    .if_read(dense_and_write_U0_pool_stream_read)
);

cnn_accelerator_start_for_conv_and_pool_U0 start_for_conv_and_pool_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_and_pool_U0_din),
    .if_full_n(start_for_conv_and_pool_U0_full_n),
    .if_write(read_input_U0_start_write),
    .if_dout(start_for_conv_and_pool_U0_dout),
    .if_empty_n(start_for_conv_and_pool_U0_empty_n),
    .if_read(conv_and_pool_U0_ap_ready)
);

cnn_accelerator_start_for_dense_and_write_U0 start_for_dense_and_write_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_and_write_U0_din),
    .if_full_n(start_for_dense_and_write_U0_full_n),
    .if_write(conv_and_pool_U0_start_write),
    .if_dout(start_for_dense_and_write_U0_dout),
    .if_empty_n(start_for_dense_and_write_U0_empty_n),
    .if_read(dense_and_write_U0_ap_ready)
);

assign ap_done = dense_and_write_U0_ap_done;

assign ap_idle = (read_input_U0_ap_idle & dense_and_write_U0_ap_idle & conv_and_pool_U0_ap_idle);

assign ap_ready = read_input_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_and_pool_U0_ap_continue = 1'b1;

assign conv_and_pool_U0_ap_start = start_for_conv_and_pool_U0_empty_n;

assign dense_and_write_U0_ap_continue = 1'b1;

assign dense_and_write_U0_ap_start = start_for_dense_and_write_U0_empty_n;

assign in_stream_TREADY = read_input_U0_in_stream_TREADY;

assign out_stream_TDATA = dense_and_write_U0_out_stream_TDATA;

assign out_stream_TDEST = dense_and_write_U0_out_stream_TDEST;

assign out_stream_TID = dense_and_write_U0_out_stream_TID;

assign out_stream_TKEEP = dense_and_write_U0_out_stream_TKEEP;

assign out_stream_TLAST = dense_and_write_U0_out_stream_TLAST;

assign out_stream_TSTRB = dense_and_write_U0_out_stream_TSTRB;

assign out_stream_TUSER = dense_and_write_U0_out_stream_TUSER;

assign out_stream_TVALID = dense_and_write_U0_out_stream_TVALID;

assign read_input_U0_ap_continue = 1'b1;

assign read_input_U0_ap_start = ap_start;

assign start_for_conv_and_pool_U0_din = 1'b1;

assign start_for_dense_and_write_U0_din = 1'b1;


reg find_df_deadlock = 0;
// synthesis translate_off
`include "cnn_accelerator_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "cnn_accelerator_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //cnn_accelerator

