-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_accelerator_dense_and_write is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pool_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    pool_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    pool_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    pool_stream_empty_n : IN STD_LOGIC;
    pool_stream_read : OUT STD_LOGIC;
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of cnn_accelerator_dense_and_write is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_done : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_idle : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_ready : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_pool_stream_read : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_918_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_918_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_817_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_817_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_716_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_716_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_615_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_615_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_514_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_514_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_413_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_413_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_312_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_312_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_211_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_211_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_110_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_110_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add9_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add9_out_ap_vld : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_done : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_idle : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_ready : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TREADY : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID : STD_LOGIC;
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call14 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_accelerator_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pool_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        pool_stream_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        pool_stream_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        pool_stream_empty_n : IN STD_LOGIC;
        pool_stream_read : OUT STD_LOGIC;
        add_918_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_918_out_ap_vld : OUT STD_LOGIC;
        add_817_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_817_out_ap_vld : OUT STD_LOGIC;
        add_716_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_716_out_ap_vld : OUT STD_LOGIC;
        add_615_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_615_out_ap_vld : OUT STD_LOGIC;
        add_514_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_514_out_ap_vld : OUT STD_LOGIC;
        add_413_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_413_out_ap_vld : OUT STD_LOGIC;
        add_312_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_312_out_ap_vld : OUT STD_LOGIC;
        add_211_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_211_out_ap_vld : OUT STD_LOGIC;
        add_110_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add_110_out_ap_vld : OUT STD_LOGIC;
        add9_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        add9_out_ap_vld : OUT STD_LOGIC );
    end component;


    component cnn_accelerator_dense_and_write_Pipeline_VITIS_LOOP_88_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        add9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_110_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_211_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_312_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_413_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_514_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_615_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_716_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_817_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        add_918_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component cnn_accelerator_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84 : component cnn_accelerator_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start,
        ap_done => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_done,
        ap_idle => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_idle,
        ap_ready => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_ready,
        pool_stream_dout => pool_stream_dout,
        pool_stream_num_data_valid => ap_const_lv3_0,
        pool_stream_fifo_cap => ap_const_lv3_0,
        pool_stream_empty_n => pool_stream_empty_n,
        pool_stream_read => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_pool_stream_read,
        add_918_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_918_out,
        add_918_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_918_out_ap_vld,
        add_817_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_817_out,
        add_817_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_817_out_ap_vld,
        add_716_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_716_out,
        add_716_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_716_out_ap_vld,
        add_615_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_615_out,
        add_615_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_615_out_ap_vld,
        add_514_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_514_out,
        add_514_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_514_out_ap_vld,
        add_413_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_413_out,
        add_413_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_413_out_ap_vld,
        add_312_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_312_out,
        add_312_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_312_out_ap_vld,
        add_211_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_211_out,
        add_211_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_211_out_ap_vld,
        add_110_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_110_out,
        add_110_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_110_out_ap_vld,
        add9_out => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add9_out,
        add9_out_ap_vld => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add9_out_ap_vld);

    grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100 : component cnn_accelerator_dense_and_write_Pipeline_VITIS_LOOP_88_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start,
        ap_done => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_done,
        ap_idle => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_idle,
        ap_ready => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_ready,
        out_stream_TREADY => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TREADY,
        add9_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add9_out,
        add_110_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_110_out,
        add_211_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_211_out,
        add_312_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_312_out,
        add_413_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_413_out,
        add_514_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_514_out,
        add_615_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_615_out,
        add_716_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_716_out,
        add_817_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_817_out,
        add_918_reload => grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_add_918_out,
        out_stream_TDATA => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TDATA,
        out_stream_TVALID => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID,
        out_stream_TKEEP => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TKEEP,
        out_stream_TSTRB => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TSTRB,
        out_stream_TUSER => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TUSER,
        out_stream_TLAST => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TLAST,
        out_stream_TID => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TID,
        out_stream_TDEST => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TDEST);

    regslice_both_out_stream_V_data_V_U : component cnn_accelerator_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TDATA,
        vld_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component cnn_accelerator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TKEEP,
        vld_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component cnn_accelerator_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TSTRB,
        vld_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component cnn_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TUSER,
        vld_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component cnn_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TLAST,
        vld_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component cnn_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TID,
        vld_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component cnn_accelerator_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TDEST,
        vld_in => grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_ignore_call14))) then 
                    grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_ready = ap_const_logic_1)) then 
                    grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_ready = ap_const_logic_1)) then 
                    grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_done, grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state6, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_done)
    begin
        if ((grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_done)
    begin
        if ((grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call14_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call14 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start <= grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_ap_start_reg;
    grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start <= grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_ap_start_reg;
    grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TREADY <= (out_stream_TREADY_int_regslice and ap_CS_fsm_state5);
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;
    out_stream_TVALID_int_regslice <= grp_dense_and_write_Pipeline_VITIS_LOOP_88_5_fu_100_out_stream_TVALID;

    pool_stream_read_assign_proc : process(grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_pool_stream_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            pool_stream_read <= grp_dense_and_write_Pipeline_VITIS_LOOP_73_1_VITIS_LOOP_74_2_VITIS_LOOP_75_3_fu_84_pool_stream_read;
        else 
            pool_stream_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
